stages:
  - Test
  - Release
  - TestRelease

Compare repls:
  stage: Test
  image:
    name: debian:bullseye
  variables:
    RENODE_VERSION: "latest"
    DASHBOARD_URL: "https://old-zephyr-dashboard.renode.io"
    DEBIAN_FRONTEND: "noninteractive"
  artifacts:
    paths:
      - ci-output/repls
      - ci-output/robot-results
    when: always
  before_script:
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy install git curl python3 python3-pip parallel xz-utils rename > /dev/null 2> /dev/null
    - mkdir -p renode-portable
    - curl -Lsf "https://builds.renode.io/renode-${RENODE_VERSION}.linux-portable.tar.gz" | tar xz -C renode-portable --strip-components=1
    - pip3 install -r renode-portable/tests/requirements.txt > /dev/null 2> /dev/null
  script:
    - python3 -m dts2repl -h
    - pip3 install .
    - mkdir -p ci-output/{repls/{dashboard,generated,diffs},dts}
    # Download DTS files from the GCP
    - |
      ZEPHYR_VERSION="$(curl -s https://zephyr-dashboard.renode.io/zephyr_sim/latest)"
      cd ci/gcp/
      pip3 install -r requirements.txt
      ./download_gcp_dts.py -c zephyr.yaml -v $ZEPHYR_VERSION -o ../../ci-output/dts/
      cd -
    # Get repl kit from dashboard
    - (cd ci-output && ../ci/get_dashboard_replkit.sh)

    # Print which dts2repl commits are being compared
    - |
      #
      OLD_COMMIT="$(<ci-output/dts2repl.version)"
      echo "Dashboard repls were generated by dts2repl $OLD_COMMIT, commits since then are:"
      git log --oneline --graph --color=always "$OLD_COMMIT..HEAD"

    # Generate and run tests
    - ./ci/test.sh

Static release:
  stage: Release
  image:
    name: debian:bullseye
  before_script:
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy install patchelf build-essential python3-pip zlib1g-dev > /dev/null 2> /dev/null
    - pip3 install pyinstaller staticx
  script:
    - pip3 install requests -t deps
    - pyinstaller --onefile dts2repl/dts2repl.py --paths deps --add-data dts2repl/models.json:. --add-data dts2repl/overlay:overlay
    - staticx dist/dts2repl dts2repl-static
    - chmod +x dts2repl-static
    - cp dist/dts2repl dts2repl-dynamic
    - chmod +x dts2repl-dynamic    
  artifacts:
    paths:
      - dts2repl-static
      - dts2repl-dynamic

Test Static release:
  stage: TestRelease
  image:
    name: debian:bullseye
  dependencies: [Static release]    
  script:
    - ./dts2repl-static https://zephyr-samples-builder.storage.googleapis.com/zephyr/063ce9caf54fa656f02ae48f3c9d537659a10dec/96b_aerocore2/hello_world/hello_world.dts --output test.repl
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy --no-install-recommends install wget ca-certificates > /dev/null 2> /dev/null
    - wget https://zephyr-samples-builder.storage.googleapis.com/zephyr/063ce9caf54fa656f02ae48f3c9d537659a10dec/96b_aerocore2/hello_world/hello_world.dts
    - ./dts2repl-static hello_world.dts --output test2.repl
    - diff test.repl test2.repl || true
    - cat test.repl
  artifacts:
    paths:
      - test.repl
      - test2.repl
