Compare repls:
  image:
    name: debian:bullseye
  variables:
    RENODE_VERSION: "latest"
    DASHBOARD_URL: "https://zephyr-dashboard.renode.io"
    DEBIAN_FRONTEND: "noninteractive"
  artifacts:
    paths:
      - ci-output/repls
      - ci-output/robot-results
    when: always
  before_script:
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy install git curl python3 python3-pip parallel xz-utils rename > /dev/null 2> /dev/null
    - mkdir -p renode-portable
    - curl -Lsf "https://builds.renode.io/renode-${RENODE_VERSION}.linux-portable.tar.gz" | tar xz -C renode-portable --strip-components=1
    - pip3 install -r renode-portable/tests/requirements.txt > /dev/null 2> /dev/null
  script:
    - pip3 install .
    - mkdir -p ci-output/{repls/{dashboard,generated,diffs},dts}
    # Get repl kit from dashboard
    - (cd ci-output && ../ci/get_dashboard_replkit.sh)

    # Print which dts2repl commits are being compared
    - |
      #
      OLD_COMMIT="$(<ci-output/dts2repl.version)"
      echo "Dashboard repls were generated by dts2repl $OLD_COMMIT, commits since then are:"
      git log --oneline --graph --color=always "$OLD_COMMIT..HEAD"

    # Generate and run tests
    - ./ci/test.sh
